class_path: src.module.ERM
init_args:
  # DataModule
  dataset: null #required
  data_dir: null #required
  num_workers: 16
  batch_size_train: 64
  batch_size_test: 64
  # ERM
  model: null #required
  activation_fn: None
  softplus_beta: 10
  learning_rate: 1e-5

  